Make G4l legacy and UEFI bootable
When I copy the efi.img from Android-x86 project and modify the 'makecd',
it didn't work;I got the info:extract efi.img and it contains some *.efi
program and contains built-in configure file as following:
search --file --set=root /.disk/info
set prefix=($root)/boot/grub
source $prefix/x86_64-efi/grub.cfg
(memdisk)/boot/grub
then it can't find .disk/info file,so can't determine which
partition is bootable,then prompt that editing the parameter.

I must create .disk/info then it can set root partition,then find
the /boot/grub/grub.cfg file and startup kernel

Signed-off-by: Jianxing Wang <wangjianxing5210@163.com>

diff --git a/makecd b/makecd
--- a/makecd
+++ b/makecd
@@ -58,7 +58,6 @@ echo "Copy rootfs files to ramdisk in /mnt"
 cp -R --preserve=all bootcd/rootfs/* /mnt
 # Added .bash_profile to run g4lmenu at start
 cp    -p bootcd/rootfs/.bash_profile /mnt
-
 echo "Umounting /mnt"
 umount /mnt
 
@@ -80,12 +79,12 @@ echo "Creating ISO9660/Joliet/RockRidge filesystem"
 
 #mkisofs -l -allow-leading-dots -V "G4L 0.53" -J -R -o boot.iso -b isolinux.bin -c boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table bootcd/isolinux/.
 genisoimage \
-  -l -V "G4L 0.53$alphaver" \
+  -vJURT -V "G4L 0.53$alphaver" \
   -o boot.iso \
   -c isolinux/boot.cat \
   -b isolinux/isolinux.bin \
-  -no-emul-boot -boot-load-size 4 -boot-info-table \
-  bootcd/isolinux/.
+  -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e boot/grub/efi.img -no-emul-boot \
+  -input-charset utf-8 bootcd/isolinux
 #   -eltorito-alt-boot \
 #   -e EFI/BOOT/syslinux.efi \
 #      -no-emul-boot \
@@ -104,6 +103,7 @@ if [ "$device" != "create" ]; then
 fi
 echo "Deleting ramdisk"
 #rm bootcd/isolinux/ramdisk.gz
-#rm bootcd/isolinux/ramdisk.lzma
+rm bootcd/isolinux/ramdisk.lzma
 echo "DONE..."
-isohybrid boot.iso||echo -e "isohybrid not found.\nInstall syslinux 4.0 or higher if you want to build a usb bootable iso."
+isohybrid --uefi boot.iso
+#isohybrid boot.iso || echo -e "isohybrid not found.\nInstall syslinux 4.0 or higher if you want to build a usb bootable iso."
